### PR TITLE
Add KubeJS TFMG to addons

### PR DESCRIPTION
**Pull request by wolfieboy09**
As of writing this, the mod is still under review, but wanted to get this completed

### CODE REVIEW

**Comment by Donaldino7712** [comment]
Will merge once the mod gets reviewed on both platforms

**Comment by wolfieboy09** [comment]
I'll let you know once they are both approved. (Submitted them almost 12 hours ago now)

**Comment by wolfieboy09** [comment]
Curseforge has approved

**Comment by wolfieboy09** [comment]
image
Modrinth finally approved

**Pull request merged**
