### PR TITLE
FTB XMod Compat page

### PR DESCRIPTION
**Pull request by FooterMan15**
This mod has ZERO damn documentation from FTB. I call lazy.

Here is my XMod documentation page.

* Todo
FTBTeamsEvents
FTBChunksEvents

### CODE REVIEW

**Comment by squoshi** [comment]
wait who are you calling lazy

**Comment by FooterMan15** [comment]
FTB

**Comment by squoshi** [comment]
fair

**Comment by FooterMan15** [comment]
Finished, merge whenever.

**Pull request merged**
